### ISSUE TITLE
Rcon passwort fix

### ISSUE THREAD

**Issue by Provokan** [cammygames/Life-Control#6]
Please can u post a fixx for Working the RCON Pass u first update doesn work. :)

**Comment by cammygames** [comment]
Add this to db.php define( 'SQ_RCON_Pass'   , 'password' ); then in views/curPlayers.php  replace this : //$Query->SetRconPassword( $SQ_RCON_Pass ); with this : $Query->SetRconPassword( SQ_RCON_Pass );

i dont remember how well the php soruce query lib worked for rcon ill mess arround with it asap after the new UI overhaul  : 

http://puu.sh/hbkO8/2026bcb91a.jpg 
http://puu.sh/hbkRW/8375052ec5.jpg
http://puu.sh/hbl50/c329a71062.png

**Comment by MightySCollins** [comment]
Love the new UI (The old one was driving me insane)

**Comment by cammygames** [comment]
Xd same thats why i have changed it today

**Comment by MightySCollins** [comment]
I know this isn't the right place to ask but did you get my email? also you need to have like 6 different faces and they can pick one when they sign up and it shows it on every page

**Comment by Provokan** [comment]
After your change my player list is empty

**Comment by cammygames** [comment]
XD i will do that and yes i did get your email and if you add me on steam we can chat more about it if you would like  https://steamcommunity.com/id/cammygames/

Also @Provokan yh id just remove it for now ima find a new rcon lib for php to use its just a pain testing it as i dont have a server to test the rcon out on properly so i can only slightly test rcon

**Comment by MightySCollins** [comment]
@Provokan Ill try rcon out soon if I can on my server. I would like to be able to add rcon so you can kick users ect

**Comment by Provokan** [comment]
So if you need a server to test them tell me about it, I can make them for a disposal.  http://steamcommunity.com/profiles/76561198029911781

**Comment by cammygames** [comment]
@MightySCollins when you have chance drop me a msg on steam and we can chat about the email also http://puu.sh/hbvPT/501c622289.jpg
