### ISSUE TITLE
Need Fixes 

### ISSUE THREAD

**Issue by Provokan** [cammygames/Life-Control#7]
Need Fixxes 
#1 - Steam Login doesn work.

Melden Sie sich mit Ihrem Steam-Account an

Note that 127.0.0.1 is not affiliated with Steam or Valve
#2 - House.ph line 95 add the button on the Language please
#3 - Missing the Staff page

---

FIXX 

template.php line 153 update this

```
                        <li>
                            <a href="profile.php">
                                <i class="fa fa-fw fa-user"></i>
                                <span><?php echo $lang['profile'];?></span>
                            </a>
                        </li>


                                              <li>
                            <a href="staff.php">
                                <i class="fa fa-fw fa-user"></i>
                                <span><?php echo $lang['staff'];?></span>
                            </a>
                        </li>
```
#4 - Missing on the editplayer.php under vehicle quick lock the "more" button :(  he was on the last update.

Update 
#1 Please change on the editplayer.php the Vehicle Quickloock with the Player informationen -> this make a bether overview

**Comment by MightySCollins** [comment]
Fixed language issues and staff page as well as slight reorder to edit player might add more back soon

**Comment by cammygames** [comment]
Yh the steam login wasn't ready as of yet i needed to write some user doc for it to make sure people remember to change it 

I've reverted Collins commit as it broke pagination and ill patch in the fixes now

**Comment by Provokan** [comment]
i use a request for fixx the steam login :)

**Comment by cammygames** [comment]
for our use case we need to use  ../
